import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import AuthProvider from "@/components/AuthPovider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Simple-CRUD-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-7 m-auto">
        <AuthProvider>
          <NavBar />
          
            <div className="p-3">{children}</div>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
